Repository rughh/on_ruby, pull requests merged in 2024-10, with the labels that each got.

#1055 fix: correct ical start/end times
  app/helpers/ical_helper.rb
  spec/helpers/ical_helper_spec.rb
Labels: bug

#1052 Update the development setup
  config/database.yml
  docker-compose.yml
  readme.md
Labels: improvement, docker

#1053 fix: changed administrate api
  app/views/admin/events/show.html.erb
Labels: bug

#1064 fix: change the name of one of the dresdenrb organizers to the nickname
  config/whitelabel.yml
Labels: bug

#1066 chore: add appsignal plugin to puma
  config/puma.rb
Labels: improvement, infrastructure
